apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: multi-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: worker
          image: 192.168.0.106:32002/multi-k8s/worker:0.1
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
